### PR TITLE
Log the position of the invalid character

### PR DESCRIPTION
**Pull request by pierDipi**

### CODE REVIEW

**Comment by pierDipi** [comment]
cc @dprotaso

**Comment by dprotaso** [comment]
nice - merge it and I can re-run it on the other repo

**Comment by pierDipi** [comment]
> nice - merge it and I can re-run it on the other repo

We're referencing [a specific tag](https://github.com/knative-sandbox/eventing-autoscaler-keda/blob/66da9998b4f067739fe2739492e1eaea042ee9c6/.github/workflows/knative-security.yaml#L53), so we need to bump it or use the main directly.

**Comment by dprotaso** [comment]
> > nice - merge it and I can re-run it on the other repo
> 
> We're referencing [a specific tag](https://github.com/knative-sandbox/eventing-autoscaler-keda/blob/66da9998b4f067739fe2739492e1eaea042ee9c6/.github/workflows/knative-security.yaml#L53), so we need to bump it or use the main directly.

oh interesting- good to know - let's bump it

**Pull request merged**
