### PR TITLE
:broom: Switch to ubi9 base image

### PR DESCRIPTION
**Pull request by cardil**
## Changes

- :broom: Switch to ubi9 base image

## Reason

Current action started to fail, as seen in: https://github.com/knative/test-infra/actions/runs/4616589202/jobs/8161790514

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
We can test it on https://github.com/pierDipi/unicode-control-characters-action-tests before cherry-picking this to release-0.1

**Comment by pierDipi** [comment]
https://github.com/pierDipi/unicode-control-characters-action-tests/pull/6

**Comment by pierDipi** [comment]
Failed with:
```
Args: -d .
usage: find_unicode_control2.py [-h] [-p {all,bidi}] [-v] [-d] [-t]
                                [-c CONFIG]
                                path [path ...]
find_unicode_control2.py: error: argument -d/--detailed: ignored explicit argument ' .'
```
maybe because the arguments changes ?

**Comment by cardil** [comment]
This is bad invoke: https://github.com/pierDipi/unicode-control-characters-action-tests/blob/main/.github/workflows/tests.yaml#L18

~It should be:~

```yaml
args: ['-d', '.']
```

It can't be like that because of how args are passed in action.yml: https://github.com/pierDipi/unicode-control-characters-action/blob/547f1027e267af69a5a910a2788d7f02c693297c/action.yml#L10-L11

**Comment by pierDipi** [comment]
It's green now: https://github.com/pierDipi/unicode-control-characters-action-tests/pull/6

**Pull request merged**
